<?php

namespace AppBundle\Repository;

use AppBundle\Document\Image;
use AppBundle\Document\ImageTag;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends MainRepository
{
    public function search($info) {
        $qb = $this->createQueryBuilder();

        if (!empty($info['filter'])) {
            $qb = $qb
                ->addAnd($qb->expr()->field('tags.tagName')->equals(new \MongoRegex("/{$info['filter']}/")))
            ;
        }

        $info['rows'] = empty($info['rows']) ? 5 : intval($info['rows']);
        $offset = empty($info['page']) ? 0 : intval($info['page']) * $info['rows'];

        $qbCount = clone $qb;
        $total = $qbCount
            ->getQuery()
            ->execute()
            ->count();

        $cursorResults = $qb
            ->skip($offset)
            ->limit($info['rows'])
            ->getQuery()
            ->execute();

        $results = [];
        if (count($cursorResults)) {
            foreach ($cursorResults as $result) {
                $results[] = $result;
            }
        }

        return [
            'records' => $total,
            'total' => intval(ceil($total / $info['rows'])),
            'results' => $results
        ];
    }
}
