<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MainRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class MainRepository extends DocumentRepository
{
    /**
     * @param $id
     * @return mixed|null
     */
    public function findOneById($id)
    {
        return $this->find($id);
    }

    /**
     * @param $document
     * @return mixed
     */
    public function refresh($document)
    {
        $this->refresh($document);
    }

    /**
     * @param $document
     * @param array $arguments
     */
    public function add($document, array $arguments = [])
    {
        $this->dm->persist($document);
        $this->dm->flush($document);
    }

    /**
     * @param $document
     * @param array $arguments
     */
    public function save($document, array $arguments = [])
    {
        $this->dm->flush($document);
    }

    /**
     * @param $document
     * @param array $arguments
     */
    public function delete($document, array $arguments = [])
    {
        $this->dm->remove($document);
        $this->dm->flush($document);
    }
}
