index:
    path: /
    defaults: { _controller: AppBundle:Default:index }

api:
    resource: "routing_api.yml"
    prefix:   /api

nelmio_apidoc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /docs
